// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: drive/rpc/rpc.proto

package drive

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelGenerateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model     string               `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Prompt    string               `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Format    string               `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Options   *ModelGenerateOption `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	Template  string               `protobuf:"bytes,5,opt,name=template,proto3" json:"template,omitempty"`
	Context   string               `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	Stream    bool                 `protobuf:"varint,7,opt,name=stream,proto3" json:"stream,omitempty"`
	KeepAlive string               `protobuf:"bytes,8,opt,name=keepAlive,proto3" json:"keepAlive,omitempty"`
}

func (x *ModelGenerateRequest) Reset() {
	*x = ModelGenerateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drive_rpc_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelGenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelGenerateRequest) ProtoMessage() {}

func (x *ModelGenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drive_rpc_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelGenerateRequest.ProtoReflect.Descriptor instead.
func (*ModelGenerateRequest) Descriptor() ([]byte, []int) {
	return file_drive_rpc_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ModelGenerateRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelGenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ModelGenerateRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ModelGenerateRequest) GetOptions() *ModelGenerateOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ModelGenerateRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *ModelGenerateRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ModelGenerateRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *ModelGenerateRequest) GetKeepAlive() string {
	if x != nil {
		return x.KeepAlive
	}
	return ""
}

type ModelGenerateOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temperature float32 `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
}

func (x *ModelGenerateOption) Reset() {
	*x = ModelGenerateOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drive_rpc_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelGenerateOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelGenerateOption) ProtoMessage() {}

func (x *ModelGenerateOption) ProtoReflect() protoreflect.Message {
	mi := &file_drive_rpc_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelGenerateOption.ProtoReflect.Descriptor instead.
func (*ModelGenerateOption) Descriptor() ([]byte, []int) {
	return file_drive_rpc_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ModelGenerateOption) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type ModelGenerateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model     string  `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	CreatedAt string  `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Response  string  `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	Done      bool    `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	Context   []int64 `protobuf:"varint,5,rep,packed,name=context,proto3" json:"context,omitempty"`
}

func (x *ModelGenerateReply) Reset() {
	*x = ModelGenerateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drive_rpc_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelGenerateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelGenerateReply) ProtoMessage() {}

func (x *ModelGenerateReply) ProtoReflect() protoreflect.Message {
	mi := &file_drive_rpc_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelGenerateReply.ProtoReflect.Descriptor instead.
func (*ModelGenerateReply) Descriptor() ([]byte, []int) {
	return file_drive_rpc_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ModelGenerateReply) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelGenerateReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ModelGenerateReply) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ModelGenerateReply) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ModelGenerateReply) GetContext() []int64 {
	if x != nil {
		return x.Context
	}
	return nil
}

type ModelChatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model     string           `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Message   string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Role      string           `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Content   string           `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Format    string           `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	Options   *ModelChatOption `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	Stream    bool             `protobuf:"varint,7,opt,name=stream,proto3" json:"stream,omitempty"`
	KeepAlive string           `protobuf:"bytes,8,opt,name=keepAlive,proto3" json:"keepAlive,omitempty"`
}

func (x *ModelChatRequest) Reset() {
	*x = ModelChatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drive_rpc_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelChatRequest) ProtoMessage() {}

func (x *ModelChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drive_rpc_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelChatRequest.ProtoReflect.Descriptor instead.
func (*ModelChatRequest) Descriptor() ([]byte, []int) {
	return file_drive_rpc_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ModelChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ModelChatRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ModelChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ModelChatRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ModelChatRequest) GetOptions() *ModelChatOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ModelChatRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *ModelChatRequest) GetKeepAlive() string {
	if x != nil {
		return x.KeepAlive
	}
	return ""
}

type ModelChatOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Temperature float32 `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
}

func (x *ModelChatOption) Reset() {
	*x = ModelChatOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drive_rpc_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelChatOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelChatOption) ProtoMessage() {}

func (x *ModelChatOption) ProtoReflect() protoreflect.Message {
	mi := &file_drive_rpc_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelChatOption.ProtoReflect.Descriptor instead.
func (*ModelChatOption) Descriptor() ([]byte, []int) {
	return file_drive_rpc_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *ModelChatOption) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type ModelChatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model     string  `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	CreatedAt string  `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Response  string  `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	Done      bool    `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	Context   []int64 `protobuf:"varint,5,rep,packed,name=context,proto3" json:"context,omitempty"`
}

func (x *ModelChatReply) Reset() {
	*x = ModelChatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drive_rpc_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelChatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelChatReply) ProtoMessage() {}

func (x *ModelChatReply) ProtoReflect() protoreflect.Message {
	mi := &file_drive_rpc_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelChatReply.ProtoReflect.Descriptor instead.
func (*ModelChatReply) Descriptor() ([]byte, []int) {
	return file_drive_rpc_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *ModelChatReply) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelChatReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ModelChatReply) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ModelChatReply) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ModelChatReply) GetContext() []int64 {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_drive_rpc_rpc_proto protoreflect.FileDescriptor

var file_drive_rpc_rpc_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x72, 0x69, 0x76, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x70, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64, 0x72, 0x69, 0x76, 0x65, 0x22, 0xfe, 0x01, 0x0a,
	0x14, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x1c, 0x0a, 0x09, 0x6b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x22, 0x37, 0x0a,
	0x13, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0xf0, 0x01, 0x0a, 0x10,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x2e,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x68, 0x61, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x22, 0x33,
	0x0a, 0x0f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x68, 0x61, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x0e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x68, 0x61,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x32, 0xa6, 0x01, 0x0a, 0x0a, 0x44, 0x72, 0x69, 0x76, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x51, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x2e, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x45, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x43, 0x68, 0x61, 0x74, 0x12, 0x17, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x2e,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x68,
	0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x21, 0x5a,
	0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x69, 0x67,
	0x70, 0x74, 0x2f, 0x73, 0x68, 0x64, 0x72, 0x69, 0x76, 0x65, 0x2f, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_drive_rpc_rpc_proto_rawDescOnce sync.Once
	file_drive_rpc_rpc_proto_rawDescData = file_drive_rpc_rpc_proto_rawDesc
)

func file_drive_rpc_rpc_proto_rawDescGZIP() []byte {
	file_drive_rpc_rpc_proto_rawDescOnce.Do(func() {
		file_drive_rpc_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_drive_rpc_rpc_proto_rawDescData)
	})
	return file_drive_rpc_rpc_proto_rawDescData
}

var file_drive_rpc_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_drive_rpc_rpc_proto_goTypes = []any{
	(*ModelGenerateRequest)(nil), // 0: drive.ModelGenerateRequest
	(*ModelGenerateOption)(nil),  // 1: drive.ModelGenerateOption
	(*ModelGenerateReply)(nil),   // 2: drive.ModelGenerateReply
	(*ModelChatRequest)(nil),     // 3: drive.ModelChatRequest
	(*ModelChatOption)(nil),      // 4: drive.ModelChatOption
	(*ModelChatReply)(nil),       // 5: drive.ModelChatReply
}
var file_drive_rpc_rpc_proto_depIdxs = []int32{
	1, // 0: drive.ModelGenerateRequest.options:type_name -> drive.ModelGenerateOption
	4, // 1: drive.ModelChatRequest.options:type_name -> drive.ModelChatOption
	0, // 2: drive.DriveProto.SendModelGenerate:input_type -> drive.ModelGenerateRequest
	3, // 3: drive.DriveProto.SendModelChat:input_type -> drive.ModelChatRequest
	2, // 4: drive.DriveProto.SendModelGenerate:output_type -> drive.ModelGenerateReply
	5, // 5: drive.DriveProto.SendModelChat:output_type -> drive.ModelChatReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_drive_rpc_rpc_proto_init() }
func file_drive_rpc_rpc_proto_init() {
	if File_drive_rpc_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_drive_rpc_rpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ModelGenerateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drive_rpc_rpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ModelGenerateOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drive_rpc_rpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ModelGenerateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drive_rpc_rpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ModelChatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drive_rpc_rpc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ModelChatOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drive_rpc_rpc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ModelChatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drive_rpc_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drive_rpc_rpc_proto_goTypes,
		DependencyIndexes: file_drive_rpc_rpc_proto_depIdxs,
		MessageInfos:      file_drive_rpc_rpc_proto_msgTypes,
	}.Build()
	File_drive_rpc_rpc_proto = out.File
	file_drive_rpc_rpc_proto_rawDesc = nil
	file_drive_rpc_rpc_proto_goTypes = nil
	file_drive_rpc_rpc_proto_depIdxs = nil
}
