// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: drive/rpc/rpc.proto

package drive

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	DriveProto_SendModelGenerate_FullMethodName = "/drive.DriveProto/SendModelGenerate"
	DriveProto_SendModelChat_FullMethodName     = "/drive.DriveProto/SendModelChat"
)

// DriveProtoClient is the client API for DriveProto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriveProtoClient interface {
	SendModelGenerate(ctx context.Context, opts ...grpc.CallOption) (DriveProto_SendModelGenerateClient, error)
	SendModelChat(ctx context.Context, opts ...grpc.CallOption) (DriveProto_SendModelChatClient, error)
}

type driveProtoClient struct {
	cc grpc.ClientConnInterface
}

func NewDriveProtoClient(cc grpc.ClientConnInterface) DriveProtoClient {
	return &driveProtoClient{cc}
}

func (c *driveProtoClient) SendModelGenerate(ctx context.Context, opts ...grpc.CallOption) (DriveProto_SendModelGenerateClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DriveProto_ServiceDesc.Streams[0], DriveProto_SendModelGenerate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &driveProtoSendModelGenerateClient{ClientStream: stream}
	return x, nil
}

type DriveProto_SendModelGenerateClient interface {
	Send(*ModelGenerateRequest) error
	Recv() (*ModelGenerateReply, error)
	grpc.ClientStream
}

type driveProtoSendModelGenerateClient struct {
	grpc.ClientStream
}

func (x *driveProtoSendModelGenerateClient) Send(m *ModelGenerateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *driveProtoSendModelGenerateClient) Recv() (*ModelGenerateReply, error) {
	m := new(ModelGenerateReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *driveProtoClient) SendModelChat(ctx context.Context, opts ...grpc.CallOption) (DriveProto_SendModelChatClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DriveProto_ServiceDesc.Streams[1], DriveProto_SendModelChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &driveProtoSendModelChatClient{ClientStream: stream}
	return x, nil
}

type DriveProto_SendModelChatClient interface {
	Send(*ModelChatRequest) error
	Recv() (*ModelChatReply, error)
	grpc.ClientStream
}

type driveProtoSendModelChatClient struct {
	grpc.ClientStream
}

func (x *driveProtoSendModelChatClient) Send(m *ModelChatRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *driveProtoSendModelChatClient) Recv() (*ModelChatReply, error) {
	m := new(ModelChatReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DriveProtoServer is the server API for DriveProto service.
// All implementations must embed UnimplementedDriveProtoServer
// for forward compatibility
type DriveProtoServer interface {
	SendModelGenerate(DriveProto_SendModelGenerateServer) error
	SendModelChat(DriveProto_SendModelChatServer) error
	mustEmbedUnimplementedDriveProtoServer()
}

// UnimplementedDriveProtoServer must be embedded to have forward compatible implementations.
type UnimplementedDriveProtoServer struct {
}

func (UnimplementedDriveProtoServer) SendModelGenerate(DriveProto_SendModelGenerateServer) error {
	return status.Errorf(codes.Unimplemented, "method SendModelGenerate not implemented")
}
func (UnimplementedDriveProtoServer) SendModelChat(DriveProto_SendModelChatServer) error {
	return status.Errorf(codes.Unimplemented, "method SendModelChat not implemented")
}
func (UnimplementedDriveProtoServer) mustEmbedUnimplementedDriveProtoServer() {}

// UnsafeDriveProtoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriveProtoServer will
// result in compilation errors.
type UnsafeDriveProtoServer interface {
	mustEmbedUnimplementedDriveProtoServer()
}

func RegisterDriveProtoServer(s grpc.ServiceRegistrar, srv DriveProtoServer) {
	s.RegisterService(&DriveProto_ServiceDesc, srv)
}

func _DriveProto_SendModelGenerate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DriveProtoServer).SendModelGenerate(&driveProtoSendModelGenerateServer{ServerStream: stream})
}

type DriveProto_SendModelGenerateServer interface {
	Send(*ModelGenerateReply) error
	Recv() (*ModelGenerateRequest, error)
	grpc.ServerStream
}

type driveProtoSendModelGenerateServer struct {
	grpc.ServerStream
}

func (x *driveProtoSendModelGenerateServer) Send(m *ModelGenerateReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *driveProtoSendModelGenerateServer) Recv() (*ModelGenerateRequest, error) {
	m := new(ModelGenerateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DriveProto_SendModelChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DriveProtoServer).SendModelChat(&driveProtoSendModelChatServer{ServerStream: stream})
}

type DriveProto_SendModelChatServer interface {
	Send(*ModelChatReply) error
	Recv() (*ModelChatRequest, error)
	grpc.ServerStream
}

type driveProtoSendModelChatServer struct {
	grpc.ServerStream
}

func (x *driveProtoSendModelChatServer) Send(m *ModelChatReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *driveProtoSendModelChatServer) Recv() (*ModelChatRequest, error) {
	m := new(ModelChatRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DriveProto_ServiceDesc is the grpc.ServiceDesc for DriveProto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriveProto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drive.DriveProto",
	HandlerType: (*DriveProtoServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendModelGenerate",
			Handler:       _DriveProto_SendModelGenerate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendModelChat",
			Handler:       _DriveProto_SendModelChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "drive/rpc/rpc.proto",
}
