// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: drive/rpc/up.proto

package drive

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arch string `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Os   string `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
}

func (x *FetchVersionRequest) Reset() {
	*x = FetchVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drive_rpc_up_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchVersionRequest) ProtoMessage() {}

func (x *FetchVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drive_rpc_up_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchVersionRequest.ProtoReflect.Descriptor instead.
func (*FetchVersionRequest) Descriptor() ([]byte, []int) {
	return file_drive_rpc_up_proto_rawDescGZIP(), []int{0}
}

func (x *FetchVersionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FetchVersionRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *FetchVersionRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type FetchVersionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *FetchVersionReply) Reset() {
	*x = FetchVersionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drive_rpc_up_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchVersionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchVersionReply) ProtoMessage() {}

func (x *FetchVersionReply) ProtoReflect() protoreflect.Message {
	mi := &file_drive_rpc_up_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchVersionReply.ProtoReflect.Descriptor instead.
func (*FetchVersionReply) Descriptor() ([]byte, []int) {
	return file_drive_rpc_up_proto_rawDescGZIP(), []int{1}
}

func (x *FetchVersionReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type FetchReleaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arch    string `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Os      string `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *FetchReleaseRequest) Reset() {
	*x = FetchReleaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drive_rpc_up_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchReleaseRequest) ProtoMessage() {}

func (x *FetchReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drive_rpc_up_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchReleaseRequest.ProtoReflect.Descriptor instead.
func (*FetchReleaseRequest) Descriptor() ([]byte, []int) {
	return file_drive_rpc_up_proto_rawDescGZIP(), []int{2}
}

func (x *FetchReleaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FetchReleaseRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *FetchReleaseRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *FetchReleaseRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type FetchReleaseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url  string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Pass string `protobuf:"bytes,3,opt,name=pass,proto3" json:"pass,omitempty"`
}

func (x *FetchReleaseReply) Reset() {
	*x = FetchReleaseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drive_rpc_up_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchReleaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchReleaseReply) ProtoMessage() {}

func (x *FetchReleaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_drive_rpc_up_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchReleaseReply.ProtoReflect.Descriptor instead.
func (*FetchReleaseReply) Descriptor() ([]byte, []int) {
	return file_drive_rpc_up_proto_rawDescGZIP(), []int{3}
}

func (x *FetchReleaseReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchReleaseReply) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *FetchReleaseReply) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

var File_drive_rpc_up_proto protoreflect.FileDescriptor

var file_drive_rpc_up_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x72, 0x69, 0x76, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x75, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64, 0x72, 0x69, 0x76, 0x65, 0x22, 0x4d, 0x0a, 0x13, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x63, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x22, 0x2d, 0x0a, 0x11, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x67, 0x0a, 0x13, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x63, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x73,
	0x73, 0x32, 0xa9, 0x01, 0x0a, 0x07, 0x55, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x4e, 0x0a,
	0x10, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x65, 0x74, 0x63, 0x68, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x4e, 0x0a,
	0x10, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x12, 0x1a, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x21, 0x5a,
	0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x69, 0x67,
	0x70, 0x74, 0x2f, 0x73, 0x68, 0x64, 0x72, 0x69, 0x76, 0x65, 0x2f, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_drive_rpc_up_proto_rawDescOnce sync.Once
	file_drive_rpc_up_proto_rawDescData = file_drive_rpc_up_proto_rawDesc
)

func file_drive_rpc_up_proto_rawDescGZIP() []byte {
	file_drive_rpc_up_proto_rawDescOnce.Do(func() {
		file_drive_rpc_up_proto_rawDescData = protoimpl.X.CompressGZIP(file_drive_rpc_up_proto_rawDescData)
	})
	return file_drive_rpc_up_proto_rawDescData
}

var file_drive_rpc_up_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_drive_rpc_up_proto_goTypes = []any{
	(*FetchVersionRequest)(nil), // 0: drive.FetchVersionRequest
	(*FetchVersionReply)(nil),   // 1: drive.FetchVersionReply
	(*FetchReleaseRequest)(nil), // 2: drive.FetchReleaseRequest
	(*FetchReleaseReply)(nil),   // 3: drive.FetchReleaseReply
}
var file_drive_rpc_up_proto_depIdxs = []int32{
	0, // 0: drive.UpProto.SendFetchVersion:input_type -> drive.FetchVersionRequest
	2, // 1: drive.UpProto.SendFetchRelease:input_type -> drive.FetchReleaseRequest
	1, // 2: drive.UpProto.SendFetchVersion:output_type -> drive.FetchVersionReply
	3, // 3: drive.UpProto.SendFetchRelease:output_type -> drive.FetchReleaseReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_drive_rpc_up_proto_init() }
func file_drive_rpc_up_proto_init() {
	if File_drive_rpc_up_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_drive_rpc_up_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FetchVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drive_rpc_up_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FetchVersionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drive_rpc_up_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FetchReleaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drive_rpc_up_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FetchReleaseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drive_rpc_up_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drive_rpc_up_proto_goTypes,
		DependencyIndexes: file_drive_rpc_up_proto_depIdxs,
		MessageInfos:      file_drive_rpc_up_proto_msgTypes,
	}.Build()
	File_drive_rpc_up_proto = out.File
	file_drive_rpc_up_proto_rawDesc = nil
	file_drive_rpc_up_proto_goTypes = nil
	file_drive_rpc_up_proto_depIdxs = nil
}
