// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: drive/rpc/up.proto

package drive

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	UpProto_SendQuery_FullMethodName = "/drive.UpProto/SendQuery"
)

// UpProtoClient is the client API for UpProto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpProtoClient interface {
	SendQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryReply, error)
}

type upProtoClient struct {
	cc grpc.ClientConnInterface
}

func NewUpProtoClient(cc grpc.ClientConnInterface) UpProtoClient {
	return &upProtoClient{cc}
}

func (c *upProtoClient) SendQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryReply)
	err := c.cc.Invoke(ctx, UpProto_SendQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpProtoServer is the server API for UpProto service.
// All implementations must embed UnimplementedUpProtoServer
// for forward compatibility
type UpProtoServer interface {
	SendQuery(context.Context, *QueryRequest) (*QueryReply, error)
	mustEmbedUnimplementedUpProtoServer()
}

// UnimplementedUpProtoServer must be embedded to have forward compatible implementations.
type UnimplementedUpProtoServer struct {
}

func (UnimplementedUpProtoServer) SendQuery(context.Context, *QueryRequest) (*QueryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendQuery not implemented")
}
func (UnimplementedUpProtoServer) mustEmbedUnimplementedUpProtoServer() {}

// UnsafeUpProtoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpProtoServer will
// result in compilation errors.
type UnsafeUpProtoServer interface {
	mustEmbedUnimplementedUpProtoServer()
}

func RegisterUpProtoServer(s grpc.ServiceRegistrar, srv UpProtoServer) {
	s.RegisterService(&UpProto_ServiceDesc, srv)
}

func _UpProto_SendQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpProtoServer).SendQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpProto_SendQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpProtoServer).SendQuery(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpProto_ServiceDesc is the grpc.ServiceDesc for UpProto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpProto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drive.UpProto",
	HandlerType: (*UpProtoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendQuery",
			Handler:    _UpProto_SendQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drive/rpc/up.proto",
}
