// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: drive/rpc/up.proto

package drive

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	UpProto_SendFetchVersion_FullMethodName = "/drive.UpProto/SendFetchVersion"
	UpProto_SendFetchRelease_FullMethodName = "/drive.UpProto/SendFetchRelease"
)

// UpProtoClient is the client API for UpProto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpProtoClient interface {
	SendFetchVersion(ctx context.Context, opts ...grpc.CallOption) (UpProto_SendFetchVersionClient, error)
	SendFetchRelease(ctx context.Context, opts ...grpc.CallOption) (UpProto_SendFetchReleaseClient, error)
}

type upProtoClient struct {
	cc grpc.ClientConnInterface
}

func NewUpProtoClient(cc grpc.ClientConnInterface) UpProtoClient {
	return &upProtoClient{cc}
}

func (c *upProtoClient) SendFetchVersion(ctx context.Context, opts ...grpc.CallOption) (UpProto_SendFetchVersionClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UpProto_ServiceDesc.Streams[0], UpProto_SendFetchVersion_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &upProtoSendFetchVersionClient{ClientStream: stream}
	return x, nil
}

type UpProto_SendFetchVersionClient interface {
	Send(*FetchVersionRequest) error
	Recv() (*FetchVersionReply, error)
	grpc.ClientStream
}

type upProtoSendFetchVersionClient struct {
	grpc.ClientStream
}

func (x *upProtoSendFetchVersionClient) Send(m *FetchVersionRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *upProtoSendFetchVersionClient) Recv() (*FetchVersionReply, error) {
	m := new(FetchVersionReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *upProtoClient) SendFetchRelease(ctx context.Context, opts ...grpc.CallOption) (UpProto_SendFetchReleaseClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UpProto_ServiceDesc.Streams[1], UpProto_SendFetchRelease_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &upProtoSendFetchReleaseClient{ClientStream: stream}
	return x, nil
}

type UpProto_SendFetchReleaseClient interface {
	Send(*FetchReleaseRequest) error
	Recv() (*FetchReleaseReply, error)
	grpc.ClientStream
}

type upProtoSendFetchReleaseClient struct {
	grpc.ClientStream
}

func (x *upProtoSendFetchReleaseClient) Send(m *FetchReleaseRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *upProtoSendFetchReleaseClient) Recv() (*FetchReleaseReply, error) {
	m := new(FetchReleaseReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UpProtoServer is the server API for UpProto service.
// All implementations must embed UnimplementedUpProtoServer
// for forward compatibility
type UpProtoServer interface {
	SendFetchVersion(UpProto_SendFetchVersionServer) error
	SendFetchRelease(UpProto_SendFetchReleaseServer) error
	mustEmbedUnimplementedUpProtoServer()
}

// UnimplementedUpProtoServer must be embedded to have forward compatible implementations.
type UnimplementedUpProtoServer struct {
}

func (UnimplementedUpProtoServer) SendFetchVersion(UpProto_SendFetchVersionServer) error {
	return status.Errorf(codes.Unimplemented, "method SendFetchVersion not implemented")
}
func (UnimplementedUpProtoServer) SendFetchRelease(UpProto_SendFetchReleaseServer) error {
	return status.Errorf(codes.Unimplemented, "method SendFetchRelease not implemented")
}
func (UnimplementedUpProtoServer) mustEmbedUnimplementedUpProtoServer() {}

// UnsafeUpProtoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpProtoServer will
// result in compilation errors.
type UnsafeUpProtoServer interface {
	mustEmbedUnimplementedUpProtoServer()
}

func RegisterUpProtoServer(s grpc.ServiceRegistrar, srv UpProtoServer) {
	s.RegisterService(&UpProto_ServiceDesc, srv)
}

func _UpProto_SendFetchVersion_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UpProtoServer).SendFetchVersion(&upProtoSendFetchVersionServer{ServerStream: stream})
}

type UpProto_SendFetchVersionServer interface {
	Send(*FetchVersionReply) error
	Recv() (*FetchVersionRequest, error)
	grpc.ServerStream
}

type upProtoSendFetchVersionServer struct {
	grpc.ServerStream
}

func (x *upProtoSendFetchVersionServer) Send(m *FetchVersionReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *upProtoSendFetchVersionServer) Recv() (*FetchVersionRequest, error) {
	m := new(FetchVersionRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _UpProto_SendFetchRelease_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UpProtoServer).SendFetchRelease(&upProtoSendFetchReleaseServer{ServerStream: stream})
}

type UpProto_SendFetchReleaseServer interface {
	Send(*FetchReleaseReply) error
	Recv() (*FetchReleaseRequest, error)
	grpc.ServerStream
}

type upProtoSendFetchReleaseServer struct {
	grpc.ServerStream
}

func (x *upProtoSendFetchReleaseServer) Send(m *FetchReleaseReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *upProtoSendFetchReleaseServer) Recv() (*FetchReleaseRequest, error) {
	m := new(FetchReleaseRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UpProto_ServiceDesc is the grpc.ServiceDesc for UpProto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpProto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drive.UpProto",
	HandlerType: (*UpProtoServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendFetchVersion",
			Handler:       _UpProto_SendFetchVersion_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SendFetchRelease",
			Handler:       _UpProto_SendFetchRelease_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "drive/rpc/up.proto",
}
